import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp,rm,readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
test('Pedidos privados, un motivo por envío, administración y horario',async t=>{
 const dir=await mkdtemp(path.join(os.tmpdir(),'oracion-'));const proc=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:'3109',ADMIN_PASSWORD:'test-secret',GEMINI_API_KEY:'',DATA_FILE:path.join(dir,'store.json')},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{proc.kill();await once(proc,'exit');await rm(dir,{recursive:true,force:true});});await once(proc.stdout,'data');
 let token='';async function api(url,method='GET',data){const r=await fetch('http://localhost:3109/api'+url,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},...(data?{body:JSON.stringify(data)}:{})});return {status:r.status,body:await r.json()};}
 assert.equal((await api('/requests')).status,401);
 assert.equal((await api('/summary','POST',{entries:[]})).status,401);
 const home=await fetch('http://localhost:3109/');assert.equal(home.status,200);assert.match(await home.text(),/Mis pedidos[\s\S]*Todos los pedidos[\s\S]*Cómo funciona/);
 assert.equal((await fetch('http://localhost:3109/backend.js')).status,200);
 assert.equal((await api('/login','POST',{password:'wrong'})).status,401);
 assert.equal((await api('/requests','POST',{name:'Ana',reasons:[{category:'Salud',text:''}]})).status,400);
 assert.equal((await api('/requests','POST',{name:'Ana',reasons:[{category:'Salud',text:'Por mi mamá.'},{category:'Familia',text:'Por mi familia.'}]})).status,400);
 assert.equal((await api('/requests','POST',{name:'Ana',reasons:[]})).status,400);
 const sent=await api('/requests','POST',{name:'Ana García',private:true,reasons:[{category:'Salud',text:'Por mi mamá.'}]});assert.equal(sent.status,201);assert.equal(sent.body.reasons.length,1);assert.equal(sent.body.number,1);assert.equal(sent.body.name,'Anónimo');
 assert.equal((await api('/mine','POST',{keys:[]})).body.length,0);assert.equal((await api('/mine','POST',{keys:[sent.body.key]})).body.length,1);
 const shared=await api('/shared-requests');assert.equal(shared.status,200);assert.equal(shared.body.length,1);assert.equal(shared.body[0].name,'Anónimo');assert.equal('key' in shared.body[0],false);assert.equal(shared.body[0].number,sent.body.number);
 assert.equal((await api('/requests/'+sent.body.id,'PATCH',{status:'Orado'})).status,401);
 const ana='a'.repeat(48),luis='b'.repeat(48),prayerUrl='/prayers/'+sent.body.id;
 const praying=(voterKey,value,extra={})=>api(prayerUrl,'PUT',{voterKey,praying:value,...extra});
 assert.equal((await praying(ana,true)).body.prayerCount,1);
 await Promise.all([praying(ana,true),praying(ana,true),praying(luis,true)]);
 const participation=(await api('/prayers','POST',{voterKey:ana,ids:[sent.body.id]})).body[0];
 assert.equal(participation.prayerCount,2);assert.equal(participation.praying,true);
 assert.equal((await api('/mine','POST',{keys:[sent.body.key]})).body[0].prayerCount,2);
 const publicPrayer=(await api('/shared-requests')).body[0];
 assert.equal(publicPrayer.prayerCount,2);assert.equal('prayers' in publicPrayer,false);assert.equal(JSON.stringify(publicPrayer).includes(ana),false);
 assert.equal((await praying(ana,false)).body.prayerCount,1);
 assert.equal((await praying(ana,false)).body.prayerCount,1);
 assert.equal((await praying(ana,true,{onlyIfMissing:true})).body.praying,false);
 assert.equal((await praying(luis,false)).body.prayerCount,0);
 assert.equal((await praying(ana,'true')).status,400);
 assert.equal((await praying('invalid',true)).status,400);
 token=(await api('/login','POST',{password:'test-secret'})).body.token;
 const list=(await api('/requests')).body;assert.equal(list.length,1);assert.equal(list[0].private,true);assert.equal('key' in list[0],false);
 assert.equal((await api('/requests/'+sent.body.id,'PATCH',{status:'Orado'})).body.status,'Orado');
 assert.equal((await api('/shared-requests')).body[0].status,'Orado');
 const today=new Date(Date.now()-3*60*60*1000).getUTCDay()||7;
 const otherDay=today===7?1:today+1;
 const schedule={mode:'weekly',days:[otherDay],start:'09:00',end:'21:00'};
 assert.equal((await api('/settings','PUT',{...schedule,end:'08:00'})).status,400);
 assert.equal((await api('/settings','PUT',schedule)).body.open,false);
 assert.equal((await api('/requests','POST',{name:'Ana',reasons:[{category:'Salud',text:'Mi motivo'}]})).status,403);
 const saved=JSON.parse(await readFile(path.join(dir,'store.json'),'utf8'));assert.equal(saved.requests[0].status,'Orado');assert.equal(saved.requests[0].name,'Anónimo');assert.equal(saved.settings.mode,'weekly');
 assert.equal((await fetch('http://localhost:3109/data/store.json')).status,404);
 await api('/settings','PUT',{mode:'open',days:[7,1,2],start:'00:00',end:'24:00'});
 token='';
 const own=(await api('/requests','POST',{name:'Prueba de borrado',reasons:[{category:'Otro motivo',text:'Motivo para borrar'}]})).body;
 assert.ok(own.number>sent.body.number);assert.equal((await api('/requests/'+own.id,'DELETE')).status,403);
 assert.equal((await api('/requests/'+own.id,'DELETE',{key:sent.body.key})).status,403);
 assert.equal((await api('/mine','POST',{keys:[own.key]})).body.length,1);
 assert.equal((await api('/requests/'+own.id,'DELETE',{key:own.key})).status,200);
 assert.equal((await api('/mine','POST',{keys:[own.key]})).body.length,0);
 assert.equal((await api('/shared-requests')).body.some(r=>r.id===own.id),false);
 token=(await api('/login','POST',{password:'test-secret'})).body.token;
 assert.equal((await api('/requests/'+sent.body.id,'DELETE')).status,200);
 assert.equal((await api('/shared-requests')).body.length,0);
 assert.equal(JSON.parse(await readFile(path.join(dir,'store.json'),'utf8')).requests.length,0);
 const before=(await api('/requests','POST',{name:'Cristian',reasons:[{category:'Salud',text:'Por mi salud'}]})).body;
 const second=(await api('/requests','POST',{name:'Cristian',reasons:[{category:'Familia',text:'Por mi familia'}]})).body;
 const arriving=(await api('/requests','POST',{name:'Ana',reasons:[{category:'Salud',text:'Pedido recién llegado'}]})).body;
 token='';assert.equal((await api('/requests','DELETE',{ids:[before.id,second.id]})).status,401);
 token=(await api('/login','POST',{password:'test-secret'})).body.token;
 assert.equal((await api('/summary','POST',{entries:[]})).status,400);
 assert.equal((await api('/summary','POST',{entries:[{id:'pedido-1',name:'Ana',reasons:['Por mi salud']}]})).status,503);
 assert.equal((await api('/requests','DELETE')).status,400);
 assert.equal((await api('/requests','DELETE',{ids:['invalid']})).status,400);
 assert.equal((await api('/requests','DELETE',{ids:[before.id,second.id,second.id]})).body.deletedCount,2);
 assert.deepEqual((await api('/shared-requests')).body.map(item=>item.id),[arriving.id]);
 assert.equal((await api('/mine','POST',{keys:[before.key,second.key]})).body.length,0);
 assert.equal((await api('/requests','DELETE',{ids:[arriving.id]})).body.deletedCount,1);
 const next=(await api('/requests','POST',{name:'Ana',reasons:[{category:'Salud',text:'Nuevo pedido'}]})).body;
 assert.equal(next.number,arriving.number+1);
});
